### ISSUE TITLE
Error starting shadowlands

### ISSUE THREAD

**Issue by fccoelho** [kayagoban/shadowlands#2]
Hi I am trying shadowlands for the first time and I am getting the following exception:

```python
$ shadowlands
Activating Shadowlands virtual environment
No Infura API Key found. Add environment variable INFURA_API_KEY to ensure continued API access. New keys are available at https://infura.io/signup
Connected to Geth/v1.8.15-omnibus-255989da/linux-amd64/go1.10.1
Bootstrapping sloader.shadowlands.eth at 0x6b600Bc4CEDF9E9845B85d9195e7470e88999B18
Collecting package info for app.shadowlands.eth
Contract reports latest checksum is 72f17fe74bbd34eb63ba1afbdc2ef41b242ca3fb50da81083b668bf440408ae8
Checksum matched cached copy of Shadowlands...
Loading Shadowlands...
Traceback (most recent call last):
  File "/home/fccoelho/.shadowlands/shadowlands.py", line 112, in <module>
    mod = importer.load_module('shadowlands')
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/__init__.py", line 34, in <module>
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/tui.py", line 64, in load
  File "/home/fccoelho/.shadowlands/lib/python3.6/site-packages/asciimatics/screen.py", line 1173, in wrapper
    return func(screen)
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/tui.py", line 55, in tui
  File "/home/fccoelho/.shadowlands/lib/python3.6/site-packages/asciimatics/screen.py", line 1353, in play
    self.draw_next_frame(repeat=repeat)
  File "/home/fccoelho/.shadowlands/lib/python3.6/site-packages/asciimatics/screen.py", line 1451, in draw_next_frame
    effect.update(self._frame)
  File "/home/fccoelho/.shadowlands/lib/python3.6/site-packages/asciimatics/effects.py", line 71, in update
    self._update(frame_no)
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/effects/dynamic_cursor.py", line 35, in _update
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/effects/cursor.py", line 132, in _update
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/effects/cursor.py", line 110, in _update_thread
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/effects/dynamic_cursor.py", line 18, in get_buffer
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/effects/dynamic_cursor.py", line 11, in need_new_buffer
  File "/home/fccoelho/.shadowlands/lib/python3.6/site-packages/asciimatics/renderers.py", line 269, in rendered_text
    return self._render_now()
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/tui/renderers.py", line 18, in _render_now
  File "/home/fccoelho/.shadowlands/cache/shadowlands-v0.12a.zip/shadowlands/eth_node.py", line 80, in network_name
KeyError: '1539104825824'
```

**Comment by kayagoban** [comment]
Somehow, the web3 client returned " 1539104825824" for the value of  w3.version.network.  I am perplexed as to how this would happen.

Is this a  repeatable or intermittent bug?

**Comment by kayagoban** [comment]
Also, could you tell me your platform (macos or linux version) and python version?  (python3 --version)

**Comment by fccoelho** [comment]
I am on Ubuntu Linux and installed from the .deb package.
My python version is 3.6.6

**Comment by fccoelho** [comment]
I think I figured out what it was.

I had a private blockchain client running (ganache-cli) listening at 127.0.0.1:8545 
so shadowlands was probably trying to connect to it.
After I stopped ganache-cli, shadowlands started normally

**Comment by kayagoban** [comment]
That's interesting.  Thanks for giving me an update on this - I'll go ahead and close this one.
