### ISSUE TITLE
Error while sending from Trezor

### ISSUE THREAD

**Issue by carver** [kayagoban/shadowlands#8]
```
$ python -m shadowlands
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jcarver/code/shadowlands-core/shadowlands/__init__.py", line 34, in <module>
    interface.load()
  File "/home/jcarver/code/shadowlands-core/shadowlands/tui/tui.py", line 64, in load
    screen = Screen.wrapper(self.tui)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/screen.py", line 1173, in wrapper
    return func(screen)
  File "/home/jcarver/code/shadowlands-core/shadowlands/tui/tui.py", line 55, in tui
    screen.play(scenes, stop_on_resize=True)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/screen.py", line 1353, in play
    self.draw_next_frame(repeat=repeat)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/screen.py", line 1436, in draw_next_frame
    event = scene.process_event(event)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/scene.py", line 101, in process_event
    event = effect.process_event(event)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/widgets.py", line 878, in process_event
    event = self._layouts[self._focus].process_event(event, self._hover_focus)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/widgets.py", line 1198, in process_event
    self._live_col][self._live_widget].process_event(event)
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/asciimatics/widgets.py", line 3186, in process_event
    self._on_click()
  File "/home/jcarver/code/shadowlands-core/shadowlands/tui/effects/widgets.py", line 95, in <lambda>
    layout2.add_widget(Button("Sign Tx", lambda: ok_func(self._gas_price_wei)), 0)
  File "/home/jcarver/code/shadowlands-core/shadowlands/tui/effects/widgets.py", line 226, in _ok
    rx = self._interface.node.send_ether(address_text._value, Decimal(amount_text._value), gas_price_wei)
  File "/home/jcarver/code/shadowlands-core/shadowlands/eth_node.py", line 309, in send_ether
    signed_tx = self._credstick.signTx(tx_dict)
  File "/home/jcarver/code/shadowlands-core/shadowlands/credstick/trezor_ethdriver.py", line 223, in signTx
    int(_s.hex(), 16)
  File "/home/jcarver/code/shadowlands-core/shadowlands/credstick/__init__.py", line 140, in signed_tx
    enctx = encode_transaction(transaction_dict, (v, r, s))
  File "/home/jcarver/code/shadowlands-core/venv/lib/python3.6/site-packages/eth_account/internal/transactions.py", line 52, in encode_transaction
    chain_naive_transaction = dissoc(unsigned_transaction.as_dict(), 'v', 'r', 's')
AttributeError: 'dict' object has no attribute 'as_dict'

$ git log -1
commit e04b2bd90d3a5a02679f20b6d5c56c84ed4c0b7e (HEAD -> master, tag: 0.16a, upstream/master, upstream/HEAD)
Author: C. Thomas <cthomas@soykaf.digital>
Date:   Sat Nov 17 07:47:52 2018 -0600

    Version bump to sync with release tag

$ pip freeze
asciimatics==1.9.1.dev105+g760274f
attrdict==2.0.0
bitcoin==1.1.42
certifi==2018.8.24
chardet==3.0.4
Click==7.0
cryptocompy==0.1.1.dev1
cytoolz==0.9.0.1
ecdsa==0.13
ECPy==0.9.1
eth-abi==1.2.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
ethereum==1.0.8
ethjsonrpc==0.3.0
future==0.16.0
hexbytes==0.1.0
hidapi==0.7.99.post21
idna==2.7
ledgerblue==0.1.20
libusb1==1.6.6
lru-dict==1.1.6
mnemonic==0.18
numpy==1.15.2
parsimonious==0.8.0
pathlib==1.0.1
pbkdf2==1.3
Pillow==5.2.0
pkg-resources==0.0.0
protobuf==3.6.1
py-solc==3.1.0
pyblake2==1.1.2
pycryptodome==3.6.6
pycryptodomex==3.6.6
pyethash==0.1.27
pyfiglet==0.7.5
pyperclip==1.7.0
pysha3==1.0.2
python-u2flib-host==3.0.3
PyYAML==3.13
qrcode==6.1.dev0
repoze.lru==0.7
requests==2.20.1
rlp==1.0.2
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
trezor==0.10.2
urllib3==1.23
wcwidth==0.1.7
web3==4.7.2
websockets==6.0
wget==3.2
```

**Comment by kayagoban** [comment]
I’m certain this isn’t happening anymore.
